{{- if .Values.database.mongodb.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  labels:
    app: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo:6.0.7
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: "admin"
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: "admin"
            - name: MONGO_INITDB_DATABASE
              value: "mediator"
          volumeMounts:
            - name: mongodb-scripts
              mountPath: /docker-entrypoint-initdb.d
              readOnly: true
      volumes:
        - name: mongodb-scripts
          configMap:
            name: mongodb-cm
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-cm
data:
  initdb.js: |
    db.createUser({
        user: "admin",
        pwd: "admin",
        roles: [
            { role: "readWrite", db: "mediator" }
        ]
    });
    const database = 'mediator';
    const collectionDidAccount = 'user.account';
    const collectionMessages = 'messages';
    const collectionMessagesSend = 'messages.outbound';
    use(database);
    db.createCollection(collectionDidAccount);
    db.createCollection(collectionMessages);
    db.createCollection(collectionMessagesSend);
    //create index
    db.getCollection(collectionDidAccount).createIndex({ 'did': 1 }, { unique: true });
    // Only enforce uniqueness on non-empty arrays
    db.getCollection(collectionDidAccount).createIndex({ 'alias': 1 }, { unique: true , partialFilterExpression: { "alias.0": { $exists: true } }});
    db.getCollection(collectionDidAccount).createIndex({ "messagesRef.hash": 1, "messagesRef.recipient": 1 });
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: "{{ .Release.Namespace }}"
spec:
  selector:
    app: mongodb
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
---
{{- end }}
