apiVersion: v1
kind: Service
metadata:
  name: mediator-service
  namespace: "{{ .Release.Namespace }}"
  labels:
    app.kubernetes.io/name: prism-mediator-server
    app.kubernetes.io/service: prism-mediator-server-main
    {{ template "labels.common" . }}
spec:
  selector:
    app.kubernetes.io/name: prism-mediator-server
  ports:
    - protocol: "TCP"
      port: 8080
      targetPort: 8080
  type: ClusterIP

---

{{- if .Values.ingress.enabled }}
kind: Service
apiVersion: v1
metadata:
  name:  mediator-domain-name-fake-service
  namespace: "{{ .Release.Namespace }}"
  annotations:
    external-dns.alpha.kubernetes.io/hostname: "{{ join ", " .Values.ingress.applicationUrls }}"
  labels:
    app.kubernetes.io/name: prism-mediator-server
    app.kubernetes.io/service: prism-mediator-server-domain-name-fake-service
    {{ template "labels.common" . }}
spec:
  type: ExternalName
  externalName: {{ .Values.ingress.platformIngressUrl }}
{{- end }}
