ingress:
  enabled: true
  
  applicationUrls:
    - chart-base-identus-mediator.atalaprism.io  # these are place holder
  platformIngressUrl: chart-base-platform-ingress.atalaprism.io  # these are place holder
  cors:
    enabled: true
    allow_origins: "*"
  consumers: []

secrets:
  secretStore: chart-base-secretstore
  dockerRegistryToken: chart-base-docker-registry-token

server:
  image:
    repository: ghcr.io
    pullPolicy: IfNotPresent
    tag: input-output-hk/atala-prism-mediator
  resources:
    limits:
      cpu: 500m
      memory: 1024Mi
    requests:
      cpu: 250m
      memory: 512Mi
  # Additional environment variables to be added to the server container
  additionalEnvVariables: {}

database:
  mongodb:
    enabled: true
