name: Release

concurrency:
  group: release

on:
  workflow_call:
    inputs:
      release-branch:
        required: false
        type: string
        default: "main"
  workflow_dispatch:
    inputs:
      release-branch:
        description: "Branch to release from"
        required: false
        default: "main"

jobs:
  release:
    env:
      GITHUB_ACTOR: "hyperledger-bot"
      GITHUB_ACTOR_EMAIL: "hyperledger-bot@hyperledger.org"
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.IDENTUS_CI }}
          ref: ${{ github.event.inputs.release-branch }}
          fetch-depth: 0

      - name: Setup Java and Scala
        uses: olafurpg/setup-scala@v14
        with:
          java-version: openjdk@1.11

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"

      - name: Setup Helm
        uses: azure/setup-helm@v3
        with:
          version: "3.12.2" # default is latest (stable)

      - name: Setup yq - portable yaml processor
        uses: mikefarah/yq@v4.34.2

      - name: Setup Scala.JS
        uses: japgolly/setup-scalajs@v1

      - name: Cache sbt
        uses: coursier/cache-action@v6.3

      - uses: crazy-max/ghaction-import-gpg@v6
        id: import_gpg
        with:
          gpg_private_key: ${{ secrets.HYP_BOT_GPG_PRIVATE }}
          passphrase: ${{ secrets.HYP_BOT_GPG_PASSWORD }}
          git_user_signingkey: true
          git_commit_gpgsign: true
          git_config_global: true
          git_tag_gpgsign: false

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ env.GITHUB_ACTOR }}
          password: ${{ env.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Release
        env:
          GIT_AUTHOR_EMAIL: ${{ steps.import_gpg.outputs.email }}
          GIT_COMMITTER_EMAIL: ${{ steps.import_gpg.outputs.email }}
          GIT_AUTHOR_NAME: ${{ steps.import_gpg.outputs.name }}
          GIT_COMMITTER_NAME: ${{ steps.import_gpg.outputs.name }}
          GITHUB_TOKEN: ${{ secrets.IDENTUS_CI }}
        run: |
          npm install
          npx semantic-release
