# See https://github.com/marketplace/actions/sbt-dependency-submission
name: Update Dependency Graph
on:
  # push:
  #   branches:
  #     - master # default branch of the project
  schedule:
    - cron: "0 20 * * *"
  workflow_dispatch:
permissions:
  contents: read
jobs:
  dependency-graph:
    name: Update Dependency Graph
    runs-on: ubuntu-latest # or windows-latest, or macOS-latest
    permissions:
      contents: write
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920 # v2.20.0
        with:
          egress-policy: audit

      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Setup Java and Scala
        uses: olafurpg/setup-scala@32ffa16635ff8f19cc21ea253a987f0fdf29844c # v14
        with:
          java-version: openjdk@1.17.0
      - name: Setup Node
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: "18" # or whatever
      - name: Setup Scala.JS
        uses: japgolly/setup-scalajs@f530918424acb5cca3d46ccd8f6d6a35f5654fd3 # v1
      - name: Cache sbt
        uses: coursier/cache-action@95e5b1029b6b86e7bac033ee44a0697d8a527d2d # v8.1.1
      - name: npm install
        run: npm install
      - uses: scalacenter/sbt-dependency-submission@d84eef4c09e633bcf5f113bcad7fd5e9af1baee9 # v3.2.3
        with:
          working-directory: ./
          #  modules-ignore:
          #    identus-mediator_3
          #    mediator_3
          #    webapp_sjs1_3
          configs-ignore: test scala-tool scala-doc-tool
